### ISSUE TITLE
webhook_request_latencies_bucket metric keeps adding new data series and became unusable

### ISSUE THREAD

**Issue by r0bj** [tektoncd/pipeline#3171]
# Expected Behavior
Prometheus metric `webhook_request_latencies_bucket` is usable in real environment, don't add new data series forever. Prometheus is able to query that metric.

# Actual Behavior
Prometheus metric `webhook_request_latencies_bucket` creates so many data series that is practically impossible to query in prometheus (too much data). It keeps adding new series while it's running so number of series increase forever. Restart pod `tekton-pipelines-webhook` resets number of series and fixes issue.

# Steps to Reproduce the Problem
Run `tekton-pipelines-webhook`.

# Additional Info

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.12.0
Pipeline version: v0.15.0
Triggers version: v0.7.0
```

**Comment by ywluogg** [comment]
I can take a look at it if no one else is. But it may take a longer time for me.

**Comment by ywluogg** [comment]
@ImJasonH will this be suitable as a good first issue?

**Comment by ImJasonH** [comment]
/assign ywluogg

cc @NavidZ since this relates to metrics

**Comment by eddie4941** [comment]
Dropping this here for context. The `webhook_request_latencies_bucket` metrics is heavily influenced by the labels in question here: https://github.com/knative/pkg/pull/1464/files

Removing the labels in that pull request might help reduce the number of unique `webhook_request_latencies_bucket` metrics the webhook has to manage. 

Aside from this, I don't know if theres a way to configure the metrics code to purge metrics from the in memory store after a period of time. This would help too. Most of the time, the in memory stuff is sent to a backend like Prometheus, stack driver, etc anyway.

**Comment by ibexmonj** [comment]
hey folks, I am curious if what i reported here https://github.com/tektoncd/pipeline/issues/3739 about some of the pipeline metrics is relevant to this discussion.

**Comment by jerop** [comment]
@ywluogg are you still looking into this?

@vdemeester looks like this issue would be addressed by [TEP-0073: Simplify metrics](https://github.com/tektoncd/community/blob/main/teps/0073-simplify-metrics.md#references-optional), right?

**Comment by ywluogg** [comment]
Hi jerop@ I'm not looking into this anymore. Please unassign me. Thanks!

**Comment by syurevich** [comment]
We have a very similar problem. Many metrics have a `resource_namespace` label. In our case, these namespaces have randomly generated names and live for a short time. This leads to a very high cardinality for the  `resource_namespace` label in about one week. That huge number of series results in a growing memory consumption.

I agree with @eddie4941 that configuring the metrics code to purge metrics from the in memory store after a period of time would help.

**Comment by pritidesai** [comment]
Based on the discussion in the API WG:
/assign @khrm

**Comment by khrm** [comment]
@pritidesai This was fixed by https://github.com/knative/pkg/pull/1464

So we can close this.

/close

**Comment by syurevich** [comment]
@khrm not only `resource_name` label but also `resource_namespace` label can contribute to this "high cardinality" issue. To fix it for every use case one would need to purge metrics from the in memory store after a period of time.

**Comment by syurevich** [comment]
This issue is still relevant. See [this comment](https://github.com/tektoncd/pipeline/issues/3171#issuecomment-1562548868).

**Comment by zhouhaibing089** [comment]
We have the same issue, too.

I have a proposal for knative/pkg at https://github.com/knative/pkg/pull/2931.

**Comment by zhouhaibing089** [comment]
knative/pkg now gives the option to exclude arbitrary tags. I assume the next action item is to bump knative/pkg and customize the webhook options.

**Comment by khrm** [comment]
@afrittoli This seems to be resolved. Will be fixed by knative update.

**Comment by Parsavali** [comment]
Do you know when this fix is expected to be part of Tekton?

**Comment by zhouhaibing089** [comment]
FWIW, besides bumping `knative.dev/pkg`, it is also necessary to override the default StatReporter options.

**Comment by zhouhaibing089** [comment]
Since #7989 is in, I am sending #8033 as a followup which actually addresses this issue.

I could anticipate that there might be asks to make it as a configuration option, and maybe off by default, so if any pointers would be greatly appreciated.

**Comment by khrm** [comment]
I think this was resolved upstream. Let me check

**Comment by khrm** [comment]
Knative removed this metrics tag:: <b style="font-weight:normal;" id="docs-internal-guid-0ecc9a62-7fff-d2b5-ac4f-ebc068e56007"><div dir="ltr" style="margin-left:0pt;" align="center">
resource_namespace | Kubernetes Namespace of the Resource | AdmissionRequest | This is being removed due to high cardinality
-- | -- | -- | --


</div></b>

Reference doc: https://docs.google.com/document/d/1QQ_ubc0RjeZbRHdN4rQR85Z7RZfTSjz4GoKsE0dZ2Z0/edit?tab=t.0
