### ISSUE TITLE
Old resource deletion hangs when `alpha` flag is off

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#5203]
# Expected Behavior

Users should be able to delete any taskrun object using `kubectl delete tr --all` no matter if `alpha` feature flag is enabled.

# Actual Behavior
After a new pipeline controller is deployed with `alpha` feature flag off, `kubectl delete tr --all` command hangs on the taskruns that worked fine under previous controller with `alpha` feature flag enabled.

# Steps to Reproduce the Problem
1. Clone the pipeline repo. Change `stable` feature flag to `alpha` in this [file](https://github.com/tektoncd/pipeline/blob/b2e3cfe786786f6b061f44dd1cc67ec8130b4d68/config/config-feature-flags.yaml#L80). 
2. Run `ko apply -R -f config/`
3. After the new controller is running, run [the example yaml](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/alpha/pipeline-object-param-and-result.yaml). You can see the pipelinerun will be successfully executed.
4. Back to step 1, change the flag back to `stable`
5. Rerun step 2
6. Run `kubectl delete tr --all` to delete all taskruns that were previously created. You will see the deletion is hanging.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12-gke.1500", GitCommit:"6c11aec6ce32cf0d66a2631eed2eb49dd65c89f8", GitTreeState:"clean", BuildDate:"2022-05-11T09:25:37Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
  WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  latest main
  ```

**Comment by vdemeester** [comment]
@chuangw6 any additionnal elements you can see ? Can you share the logs of the controller and webhook ?

**Comment by abayer** [comment]
I can't reproduce this - deletion went through right away for me...

**Comment by chuangw6** [comment]
Hi @vdemeester ,
- [controller log](https://gist.github.com/chuangw6/1549c92aae38c16c1ab17ae3bbc50bc8)
- [webhook log](https://gist.github.com/chuangw6/c1907a1d1f10a2962e9718b0c21ca4fd).

If you search the keyworkd `alpha` in the controller log, you can see the complaints about it. This alpha flag was added [here](https://github.com/tektoncd/pipeline/blob/e1153a1e7eea902183280eeb6797924c104dda13/pkg/apis/pipeline/v1beta1/task_validation.go#L276-L286).

**Comment by chuangw6** [comment]
> I can't reproduce this - deletion went through right away for me...

Hi @abayer ,
Instead of following step 4 & 5 to turn off alpha flag, can you try to just apply the latest release to see if you can reproduce? Thanks

`kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.38.0/release.yaml`

**Comment by abayer** [comment]
@chuangw6 Aaaaah - that's fixed in #5215.

**Comment by chuangw6** [comment]
> @chuangw6 Aaaaah - that's fixed in #5215.

Thanks @abayer for the pointer. I pulled the latest main and followed the above steps. 
Now the controller doesn't have the complaints, but deleting the old taskruns still hangs.

Any idea?

**Comment by abayer** [comment]
I was looking at the webhook logs, which is where I saw the conversion errors. Could you post your new webhook log with latest main?

**Comment by abayer** [comment]
Aaaah, I see https://gist.github.com/chuangw6/c1907a1d1f10a2962e9718b0c21ca4fd#file-pipeline-webhook-log-L342 - that's a problem for sure, but it's fixed in #5210.

**Comment by chuangw6** [comment]
> I was looking at the webhook logs, which is where I saw the conversion errors. Could you post your new webhook log with latest main?

sure!
- [new webhook log](https://gist.github.com/chuangw6/7c68774399baaf689a7bc0aa189c5ded)
- [new controller log](https://gist.github.com/chuangw6/fc60625c07f0bb8d821eda3bdcbf898b)

**Comment by abayer** [comment]
Interesting - https://gist.github.com/chuangw6/7c68774399baaf689a7bc0aa189c5ded#file-new-webhook-log-L276 is there, with references to Chains, though I think that's just service account stuff?

**Comment by chuangw6** [comment]
> Interesting - https://gist.github.com/chuangw6/7c68774399baaf689a7bc0aa189c5ded#file-new-webhook-log-L276 is there, 

Interesting. Why can pipeline controller pick up chains-related stuff? lol

This is [chains Controller log](https://gist.github.com/chuangw6/049920c48b73c3cf2aa50248927877c7). It complaints about alpha flag too.

> with references to Chains, though I think that's just service account stuff?

But the line`[system:serviceaccounts system:serviceaccounts:tekton-chains system:authenticated]` says it's authenticated.

**Comment by vdemeester** [comment]
It's on an `UPDATE` event, so it does validation and fails there. Chains tries to update the object, but cannot because some fields are behind alpha and stable is set. I am not sure why it would *block* deletion, except maybe if it fails to sign, put the object into the queue to retry, making it somehow un-deletable ?

@chuangw6 can you try to disable chains and see if that happens ?

**Comment by chuangw6** [comment]
> It's on an `UPDATE` event, so it does validation and fails there. Chains tries to update the object, but cannot because some fields are behind alpha and stable is set. I am not sure why it would _block_ deletion, except maybe if it fails to sign, put the object into the queue to retry, making it somehow un-deletable ?
> 
> @chuangw6 can you try to disable chains and see if that happens ?

Hi @vdemeester,
I tried two things:

1. Had a new cluster with only pipeline installed. No resource deletion hanging problem at all under either `stable` or `alpha` flag.

2. Tried to disable chains in my old cluster where both chains and pipelines are installed.
I tried to disable chains by two ways 
   - scale the controller 0. 
   - delete all the resources under chains namespace by running `ko delete -R -f config/`. 

   Neither of them works. And things even get tricker: after chains is disabled, I cannot delete the taskruns after `alpha` is turn on again.

**Comment by wlynch** [comment]
> It's on an UPDATE event, so it does validation and fails there. Chains tries to update the object, but cannot because some fields are behind alpha and stable is set. I am not sure why it would block deletion, except maybe if it fails to sign, put the object into the queue to retry, making it somehow un-deletable ?

^ @vdemeester this is correct. Chains uses a finalizer to make sure that Run objects don't disappear before they can be attested. Normally, the finalizer is removed once chains has processed the object, but because the alpha flag was disabled, chains can't complete its reconcile (probably when trying to add the `chains.tekton.dev/signed` annotation) so the finalizer is never removed.

I don't think chains is unique here - any client that tries to update a beta object with alpha fields would fail in a similar way.  This kind of unexpected behavior was what I was worried about in https://github.com/tektoncd/pipeline/pull/5005#issuecomment-1170484289 (cc @lbernick @afrittoli)

**Comment by chuangw6** [comment]
> ^ @vdemeester this is correct. Chains uses a finalizer to make sure that Run objects don't disappear before they can be attested. Normally, the finalizer is removed once chains has processed the object, but because the alpha flag was disabled, chains can't complete its reconcile (probably when trying to add the chains.tekton.dev/signed annotation) so the finalizer is never removed.

Thanks @wlynch . That explains why it's still not deletable after chains is disabled - because the taskruns have been added a finalizer. 

Quick question: When a client like chains is trying to add a finalizer to the object, it's an UPDATE operation. And whenever update operation happens, pipeline's webhook will be triggered in which alpha flag is checked. Is that correct understanding?


<img src="https://user-images.githubusercontent.com/30398455/181662442-c93dddff-d08b-455b-b459-fa95cc3f8846.png" width="500" height="300">

**Comment by chuangw6** [comment]
FYI: For those who want to delete the taskruns that hang because of the finalizer, you can use the patch command to remove finalizer, which can help remove resources immediately.

```
kubectl patch tr/<NAME-OF-THE-TASKRUN-OBJECT> --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
```

**Comment by vdemeester** [comment]
@wlynch this is solely on the `v1beta1` object (with or without the api fields to alpha or not). Quick question, is `chains` using `PATCH` ? I think we "could" detect it's a PATCH on metadata and not run the validation.
In any case, this is one "potential" problem we have with `enable-api-fields`, if users enable `alpha` API to try something and switch back to `stable` with an object with alpha api fields, that are, thus, not valid anymore. Maybe the webhook could "annotate" objects depending on whether it adds `enable-api-fields` to alpha (or to any value), so that on later validation, we could act based on that ? 🤔

**Comment by vdemeester** [comment]
> Quick question: When a client like chains is trying to add a finalizer to the object, it's an UPDATE operation. And whenever update operation happens, pipeline's webhook will be triggered in which alpha flag is checked. Is that correct understanding?

I think it really depends on when you switch back the `enable-api-fields` to `stable`. If it's during the execution of a `TaskRun`, then chains will pick it up once done and.. updating it will fail the validation. I think it also might depend when `chains` put the finalizer in.

**Comment by lbernick** [comment]
I think this should be fixed by https://github.com/tektoncd/pipeline/pull/5610; @chuangw6 are you able to check whether this is still happening?

**Comment by chuangw6** [comment]
Hey @lbernick ,

I just tried on the latest main. It seems the issue still persists because of the reason above mentioned by @wlynch. 

> ^ @vdemeester this is correct. Chains uses a finalizer to make sure that Run objects don't disappear before they can be attested. Normally, the finalizer is removed once chains has processed the object, but because the alpha flag was disabled, chains can't complete its reconcile (probably when trying to add the chains.tekton.dev/signed annotation) so the finalizer is never removed.
> I don't think chains is unique here - any client that tries to update a beta object with alpha fields would fail in a similar way. This kind of unexpected behavior was what I was worried about in https://github.com/tektoncd/pipeline/pull/5005#issuecomment-1170484289 (cc @lbernick @afrittoli)
